defaults: &defaults
  working_directory: ~/incapsula-cracker-py3

version: 2
jobs:
  build:
    <<: *defaults
    docker:
      - image: ubuntu:14.04
    steps:
      - run:
        command: "apt-get -y update && apt-get install -y git"
      - checkout
  build-p27:
    <<: *defaults
    docker:
      - image: python:2.7
    steps:
      - run:
        command: "apt-get -y update && apt-get install -y git"
      - checkout
  build-p34:
    <<: *defaults
    docker:
      - image: python:3.4
    steps:
      - run:
        command: "apt-get -y update && apt-get install -y git"
      - checkout

workflows:
  version: 2
  build_and_test:
    jobs:
      - build-p27
      - build-p34