version: 2
jobs:
  build:
    working_directory: ~/incapsula-cracker-py3
    docker:
      - image: ubuntu:14.04
      - image: python:3.4
    steps:
      - checkout
  p27:
    working_directory: ~/incapsula-cracker-py3
    docker:
      - image: ubuntu:14.04
      - image: python:2.7
    steps:
      - run: printf Using: && python --version
  p34:
    working_directory: ~/incapsula-cracker-py3
    docker:
      - image: ubuntu:14.04
      - image: python:3.4
    steps:
      - run: printf Using: && python --version

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - p27
      - p34
