version: 2
jobs:
  build:
    working_directory: ~/incapsula-cracker-py3
    docker:
      - image: python:3.4
    steps:
      - checkout
      - run:
        name: Trigger Jobs
        command:
          trigger_job build-p27
          trigger_job build-p34
  build-p27:
    docker:
      - image: python:2.7
    working_directory: ~/incapsula-cracker-py3
    steps:
      - run:
        command: |
          printf "Using: " && python --version
  build-p34:
    docker:
      - image: python:3.4
    working_directory: ~/incapsula-cracker-py3
    steps:
      - run:
        command: |
          printf "Using: " && python --version
